[package]
name = "cachecow"
version = "0.1.1"
edition = "2024"
description = "A stupid simple JSON key-value filesystem cache."
repository = "https://github.com/uncenter/cachecow"
license = "MIT"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2"

[dev-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
user_dirs = "0.2.0"
